/**
* @description Constant values class
*/
public class SOM_CancelPaymentAuthorizationConstants {
    public static final String ADYEN_NAME = 'Adyen';
    public static final String ADYEN_COMPONENT = 'Adyen_Component';
    public static final String AUTHORIZATION_RELEASED = 'AuthorizationReleased';
    public static final String AUTHORIZATION_CANCEL_REQUEST_FAILED = 'RequestFailed';
    public static final String AUTHORIZATION_CANCEL_REQUEST_SENT = 'RequestSent';
    public static final String AUTHORIZATIONS_TO_RECORD = 'Authorizations to record';
    public static final String AUTHORIZATIONS_TO_RECORD_RESULTS = 'Authorizations to record - Results';
    public static final String ERROR_FINDING_PAYMENT_GATEWAY_METADATA = 'No config found for this service on Payment Gateway Information metadata.';
    public static final String EVENT_AUTHORIZATION = 'AUTHORIZATION';
    public static final String EVENT_CANCELLATION = 'CANCELLATION';
    public static final String EVENT_CAPTURE = 'CAPTURE';
    public static final String FLOW_INPUT = 'Flow Input';
    public static final String HTTP_REQUEST = 'Http request';
    public static final String HTTP_RESPONSE = 'Http response';
    public static final String PAYPAL_NAME = 'Paypal';
    public static final String PAYPAL_COMPONENT = 'Paypal_Component';
    public static final String TEST_PAYMENT_GATEWAY_EXTERNAL_REFERENCE = 'TestPaymentGateway';
    public static final String TRUE_STRING = 'true';
    public static final String FALSE_STRING = 'false';
}